import os

cwd = os.getcwd()
name = input('Enter namespace: ')
des = '        "description": "Generated by tyropro\'s datapack batch file :: ' + input('Enter description: ') + '"\n'

path = os.path.join(cwd)

file = path + r'\pack.mcmeta'
with open(file, 'w') as f:
    f.write('{\n')
    f.write('    "pack":  {\n')
    f.write('        "pack_format": 7,\n')
    f.write(des)
    f.write('    }\n')
    f.write('}')

# overwrites the path variable
path = os.path.join(cwd, 'data')
os.mkdir(path)
path = os.path.join(cwd, 'data', name)
os.mkdir(path)
path = os.path.join(cwd, 'data', name, 'functions')
os.mkdir(path)
path = os.path.join(cwd, 'data', name, 'recipes')
os.mkdir(path)
path = os.path.join(cwd, 'data', name, 'advancements')
os.mkdir(path)
path = os.path.join(cwd, 'data', 'minecraft')
os.mkdir(path)
path = os.path.join(cwd, 'data', 'minecraft', 'tags')
os.mkdir(path)
path = os.path.join(cwd, 'data', 'minecraft', 'tags', 'functions')
os.mkdir(path)

file = path + r'\tick.json'
with open(file, 'w') as f:
    f.write('{\n')
    f.write('    "values":  [\n')
    f.write('        ""\n')
    f.write('    ]\n')
    f.write('}')

file = path + r'\load.json'
with open(file, 'w') as f:
    f.write('{\n')
    f.write('    "values":  [\n')
    f.write('        ""\n')
    f.write('    ]\n')
    f.write('}')